spring:
  application:
    name: payment-messages

  profiles:
    active: dev

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO}

  jms:
    listener:
      acknowledge-mode: auto

ibm:
  mq:
    queue-manager: ${MQ_QMGR}
    channel: ${MQ_CHANNEL}
    conn-name: ${MQ_CONN_NAME}
    user: ${MQ_USER}
    password: ${MQ_PASSWORD}
    receive-timeout: 5000
    queue: ${MQ_QUEUE}


server:
  port: ${SERVER_PORT}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env
  endpoint:
    health:
      show-details: when-authorized
  info:
    env:
      enabled: true

info:
  app:
    name: payment-messages
    version: 1.0.0
    java-version: 21